[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
    { id = "check-added-large-files" },
    { id = "check-toml" },
    { id = "detect-private-key" },
    { id = "trailing-whitespace" }
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.5.0"
hooks = [
    { id = "ruff" },
    { id = "ruff-format" }
]

[[repos]]
repo = "https://github.com/pre-commit/mirrors-mypy"
rev = "v1.10.0"
hooks = [
    { id = "mypy" }
]

[[repos]]
repo = "https://github.com/commitizen-tools/commitizen"
rev = "v4.13.9"
hooks = [
    { id = "commitizen", stages = ["commit-msg"] },
    { id = "commitizen-branch", stages = ["pre-push"] },
]